In [1]:
import numpy as np
np .__version__
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([1,3,5,7,9])
type(arr1)

numpy.ndarray

In [5]:
arr3 = arr1
id(arr1)

2483285376528

In [7]:
id(arr3)

2483285376528

In [9]:
arr4 = arr1.copy()
id(arr4)


2483324569520

In [11]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,20)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(10, 20, 3)


array([10, 13, 16, 19])

In [17]:
arr = np.arange(10)


In [19]:
 len(arr)

10

In [21]:
arr.size

10

In [23]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
 arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [27]:
arr[0]


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
 arr[1]


2.5

In [31]:
 np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
 np.zeros(5, dtype ='int64')


array([0, 0, 0, 0, 0], dtype=int64)

In [37]:
 arr = np.ones((2,3), dtype ='int_')

In [39]:
arr1 = np.array([111, 2.3, True, False, False])
arr1


array([111. ,   2.3,   1. ,   0. ,   0. ])

In [41]:
 arr2 = np.array([111, 2.3, 'python', 'abc'])
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [43]:
 arr3 = np.array([111, True, 'abc'])
arr3

array(['111', 'True', 'abc'], dtype='<U11')

In [45]:
a = np.array([1, 2, 3, 4, 5])
a[2]


3

In [47]:
a[-1]


5

In [49]:
 a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
 a[[0,2]]


array([[1, 2, 3],
       [7, 8, 9]])

In [53]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 )
arr[arrMask]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [55]:
 arrMask = ( ( (arr % 5) == 0 ) & ( arr >0) )
arr[arrMask]


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [57]:
 a = np.arange(15)
a.reshape(3,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
 a = a.reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [65]:
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [67]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [69]:
 a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b


array([[1, 2],
       [3, 4],
       [9, 9]])

In [71]:
 c = np.append(a, [[9], [9]] , axis=1)
c


array([[1, 2, 9],
       [3, 4, 9]])

In [73]:
 a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [75]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [77]:
np.delete(a, 0, axis = 0)


array([[4, 5, 6]])

In [79]:
np.delete(a, 1, axis = 1)


array([[1, 3],
       [4, 6]])